chrome-webdriver-path=D:/personal/mft/report-sender/chromedriver-win64/chromedriver.exe
contacts=D:/personal/mft/report-sender/run/whatsapp-contacts.xlsx
message-file=D:/personal/mft/report-sender/run/latest.txt
attachments-path=D:/personal/mft/report-sender/run/attachments