chrome-webdriver-path=D:/personal/fifty2days/mft/whatsapp-report-sender/chromedriver-win64/chromedriver.exe
contacts=D:/personal/fifty2days/mft/whatsapp-report-sender/whatsapp-contacts.xlsx
message-file=D:/personal/fifty2days/mft/whatsapp-report-sender/latest.txt
attachments-path=D:/personal/fifty2days/mft/whatsapp-report-sender/attachments